title: Thura Blog 
description: All of my personal, photos, my cat, my learning...

url: http://localhost:4000/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

collections:
  minna:
    output: true
    permalink: /minna/:path/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   facebook: thuraucsy
   email: thura.ucsy@gmail.com

google_analytics: "UA-85771286-1"
